from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import date

class ResearchData(BaseModel):
    """
    Represents a single piece of research data, like a statistic or a quote.
    """
    statistic: Optional[str] = Field(None, description="A key statistic or data point.")
    source: Optional[str] = Field(None, description="The source of the statistic.")
    quote: Optional[str] = Field(None, description="An insightful quote from a thought leader.")
    author: Optional[str] = Field(None, description="The author of the quote.")

class ResearchReport(BaseModel):
    """
    A structured report containing the findings from the research specialist.
    This model directly corresponds to the expected_output of the research_task.
    """
    topic: str = Field(..., description="The central topic of the research.")
    key_concepts: List[str] = Field(default_factory=list, description="Core concepts and definitions related to the topic.")
    trends: List[str] = Field(default_factory=list, description="Current industry trends and discussions.")
    data_points: List[ResearchData] = Field(default_factory=list, description="A list of relevant statistics and quotes.")
    potential_hooks: List[str] = Field(default_factory=list, description="Engaging angles or hooks for the content.")

class ResearchFlowState(BaseModel):
    """
    The main state object that tracks the research flow.
    This object holds the inputs for the task and stores the output.
    """
    # Inputs for the research_task
    topic: str = Field(..., description="The topic for the research task.")
    industry: str = Field(..., description="The industry space to focus the research on.")
    current_date: date = Field(default_factory=date.today, description="The current date for timely research.")
    
    # Output of the research_task
    research_report: Optional[ResearchReport] = Field(None, description="The structured report generated by the researcher agent.")
    
    # Metadata for the flow
    status: str = Field("Not Started", description="The current status of the research process.")